services:
  admin-database:
    image: mcr.microsoft.com/mssql/server:2022-CU13-ubuntu-22.04
    container_name: admin-database
    environment:
      ACCEPT_EULA: "true"
      MSSQL_SA_PASSWORD: "StrongP@ssw0rd123!"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

  admin-database-seed:
    container_name: admin-database-seed
    depends_on:
      - admin-database
    build:
      context: ./backend/src/AdminService/AdminService.Infrastructure/Database/
      dockerfile: Dockerfile

  rabbitmq:
    image: 'masstransit/rabbitmq:latest'
    container_name: rabbitmq
    ports:
      - '15672:15672'
      - '5672:5672'

volumes:
  mssql_data: