services:
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: database
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "StrongP@ssw0rd123!"
    volumes:
      - mssql_data:/var/opt/mssql
volumes:
  mssql_data: