services:
  admin-database:
    image: mcr.microsoft.com/mssql/server:2022-CU13-ubuntu-22.04
    container_name: admin-database
    environment:
      ACCEPT_EULA: "true"
      MSSQL_SA_PASSWORD: "StrongP@ssw0rd123!"
    ports:
      - "1433:1433"
    volumes:
      - admin_mssql_data:/var/opt/mssql

  admin-database-seed:
    container_name: admin-database-seed
    depends_on:
      - admin-database
    build:
      context: .
      dockerfile: ./backend/src/AdminService/AdminService.Infrastructure/Database/Dockerfile

  adminservice.api:
    container_name: adminservice.api
    build:
      context: .
      dockerfile: ./backend/src/AdminService/AdminService.Api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=admin-database;Database=AdminService;User Id=sa;Password=StrongP@ssw0rd123!;TrustServerCertificate=True;
      - Redis__ConnectionString=redis:6379
    depends_on:
      - admin-database
      - redis
  
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
  
  redis-commander:
    container_name: redis-management
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
  
volumes:
  admin_mssql_data:
  redis-data:
