services:
  database:
    image: mcr.microsoft.com/mssql/server:2022-CU13-ubuntu-22.04
    container_name: database
    environment:
      ACCEPT_EULA: "true"
      MSSQL_SA_PASSWORD: "StrongP@ssw0rd123!"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

  database-seed:
    depends_on:
      - database
    build:
      context: ./backend/src/BleepGuard.Infrastructure/Database/
      dockerfile: Dockerfile
    container_name: database-seed

volumes:
  mssql_data: