FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER $APP_UID
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src

COPY ["AdminService.sln", "./AdminService/"]
COPY ["AdminService.Api/AdminService.Api.csproj", "./AdminService.Api/"]
#COPY ["AdminService.Api/AdminService.Api.csproj", "./AdminService.Api"]
#RUN "dotnet restore AdminService.Api/AdminService.Api.csproj"
#COPY . .
# WORKDIR "/AdminService/AdminService.Api"
# RUN dotnet build "AdminService.Api.csproj" -c $BUILD_CONFIGURATION -o /app/build

# FROM build AS publish
# ARG BUILD_CONFIGURATION=Release
# RUN dotnet publish "AdminService.Api.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

# FROM base AS final
# WORKDIR /app
# COPY --from=publish /app/publish .
# ENTRYPOINT ["dotnet", "AdminService.Api.dll"]
